version: "3.4"

services:
     
  sharedb:
    image: share-db
    build: 
      context: ./ShareDB_Server/
      dockerfile: Dockerfile

    environment:
    # Environmental variables
      - PORT=8080


      # docker services inspect 
      - NODENAME={{.Node.Hostname}}
      - NODEID={{.Node.ID}}
      - SERVICEID={{.Service.ID}}
      - SERVICENAME={{.Service.Name}}
      - TASKID={{.Task.ID}}
      - TASKNAME={{.Task.Name}}
      - TASKREPID={{.Task.Slot}}
    command: npm start

    ports:
      - "8080"

    networks:
      - editor_network  

    deploy:
      mode: replicated
      replicas: 2
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.role == worker



  editor:
    image: editor
    build: 
      context: ./CodeMirror/
      dockerfile: Dockerfile  
    environment:
      # Environmental variables
      - PORT=8080
      - DBPORT=8112
      - DBHOST=sharedb

      # docker services inspect 
      - NODENAME={{.Node.Hostname}}
      - NODEID={{.Node.ID}}
      - SERVICEID={{.Service.ID}}
      - SERVICENAME={{.Service.Name}}
      - TASKID={{.Task.ID}}
      - TASKNAME={{.Task.Name}}
      - TASKREPID={{.Task.Slot}}
    
    command: npm start
    ports: 
      "8080:8080"
      "8112"

    networks:
      - editor_network  

    deploy:
      mode: replicated
      replicas: 2
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.role == worker

networks:
  editor_network: 
    driver: overlay
